name: Print

on:
  repository_dispatch:
    types: [trigger-workflow, push]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: List directory structure
      run: echo "Printed :)"
      
      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #   ref: ${{ github.event.client_payload.sha }}
