name: Print

on:
  workflow_call:
    inputs:
      example-input:
        required: true
        type: string
    
jobs:
  print:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4
    #   with:
    #   ref: ${{ github.event.client_payload.sha }}
    - name: Print Example Input
      run: echo "Input is: ${{ inputs.example-input }}"
      
      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #   ref: ${{ github.event.client_payload.sha }}
