apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: "{{ .Release.Name }}-dopplersecret"
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: {{ .Release.Name }}
  config: prod
  managedSecret:
    name: "{{ .Release.Name }}-secret-doppler"
    namespace: {{ .Release.Name }}
    type: Opaque
  resyncSeconds: 60