# Example values.yaml using portfolio data
deployment:
  replicas: 1
  image:
    repository: repository/prod
    tag: application
  registry:
    imagePullSecret: docker-registry-secret
serviceAccount:
  name: docker-registry-serviceaccount
  imagePullSecret: docker-registry-secret

ingress:
  host: website.com
  tls: true
  externalPort: 80
  internalPort: 8080

issuer:
  email: user@email.com
  server: https://acme-v02.api.letsencrypt.org/directory

pdb:
  minAvailable: 1

config:
  APP_NAME: "TEST"
