name: Approval

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    
jobs:
  approval:
    runs-on: ubuntu-latest
    environment:
        name: production 
    steps:
      - name: Wait for manual approval
        run: echo "Manual approval required for deployment."
