name: Deploy

on:
  workflow_call:
    inputs:
      valuesPath:
        required: true
        type: string
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ vars.DO_CLUSTER_NAME }}
      - name: Helm tool installer
        uses: azure/setup-helm@v4.2.0
      - name: Checkout values
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          repository: shawnweigand/devops
          path: devops
      - name: Deploy Helm chart to DOKS
        run: |
          helm upgrade --install \
          -f ${{ inputs.valuesPath }} \
          portfolio \
          ./devops/helm \
          --namespace portfolio
