name: Deploy

on:
  workflow_call:
    inputs:
      valuesPath:
        required: true
        type: string
      helmRelease:
        required: true
        type: string
      namespace:
        required: true
        type: string
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ vars.DO_CLUSTER_NAME }}
      - name: Helm tool installer
        uses: azure/setup-helm@v4.2.0
      - name: Checkout values
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          repository: shawnweigand/devops
          path: devops
      - name: Show Helm Template
        run: |
          helm template \
            -f ${{ inputs.valuesPath }} \
            ${{ inputs.helmRelease }} \
            ./devops/helm \
            --namespace ${{ inputs.namespace }}      
      - name: Deploy Helm chart to DOKS
        run: |
          helm upgrade --install \
          -f ${{ inputs.valuesPath }} \
          --set dockerConfigJson="${{ secrets.K8S_DOCKER_CONFIG_JSON }}" \
          ${{ inputs.helmRelease }} \
          ./devops/helm \
          --namespace ${{ inputs.namespace }}
