name: Testflow

on:
  workflow_call:
    inputs:
      example-input:
        required: true
        type: string
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ inputs.example-input }}"
      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.event.client_payload.sha }}
      # - name: Checkout code
      #   uses: actions/checkout@v3
      
      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #   ref: ${{ github.event.client_payload.sha }}
